### ISSUE TITLE
Sugestions

### ISSUE THREAD

**Issue by JotaRandom** [GreenRaccoon23/archdroid-icon-theme#1]
Do you acn mention in the README the theme used for those screenshoots?

also fot the size problem librsvg come with rsvg-convert wich could help with the png problems and keep this git repo small.

**Comment by GreenRaccoon23** [comment]
Do you mean the icon theme? The name for each screenshot's icon theme is above the screenshot.

**Comment by GreenRaccoon23** [comment]
Oh! Do you mean the window theme? I was using Numix-ArchBlue from the `numix-themes-archblue-git` package in the AUR.

**Comment by JotaRandom** [comment]
yeah, the window-theme, is not mentioned in the README.md.
rsvg-convert have a manpage, tango-icopn-theme use it for generation if icons.

**Comment by GreenRaccoon23** [comment]
I used `rsvg-convert` to scale some of the images, but they're still blurry for some reason unfortunately. I'll just stick to the svg images right now to keep the package small.
