### ISSUE TITLE
.INSTALL in pkgbuild wroken

### ISSUE THREAD

**Issue by JotaRandom** [GreenRaccoon23/archdroid-icon-theme#2]
´´´
/tmp/alpm_WSZ8Cm/.INSTALL: línea 3: _printf: no se encontró la orden
/tmp/alpm_WSZ8Cm/.INSTALL: línea 12: setaf: no se encontró la orden
Updating
icon
cache...
/tmp/alpm_WSZ8Cm/.INSTALL: línea 8: _printf: no se encontró la orden
/tmp/alpm_WSZ8Cm/.INSTALL: línea 12: setaf: no se encontró la orden
Archdroid-Amber
/tmp/alpm_WSZ8Cm/.INSTALL: línea 8: _printf: no se encontró la orden
/tmp/alpm_WSZ8Cm/.INSTALL: línea 12: setaf: no se encontró la orden
Archdroid-ArchBlue
/tmp/alpm_WSZ8Cm/.INSTALL: línea 8: _printf: no se encontró la orden
/tmp/alpm_WSZ8Cm/.INSTALL: línea 12: setaf: no se encontró la orden
Archdroid-Blue
/tmp/alpm_WSZ8Cm/.INSTALL: línea 8: _printf: no se encontró la orden
/tmp/alpm_WSZ8Cm/.INSTALL: línea 12: setaf: no se encontró la orden
Archdroid-BlueGrey
/tmp/alpm_WSZ8Cm/.INSTALL: línea 8: _printf: no se encontró la orden
/tmp/alpm_WSZ8Cm/.INSTALL: línea 12: setaf: no se encontró la orden
Archdroid-Brown
/tmp/alpm_WSZ8Cm/.INSTALL: línea 8: _printf: no se encontró la orden
/tmp/alpm_WSZ8Cm/.INSTALL: línea 12: setaf: no se encontró la orden
Archdroid-Cyan
/tmp/alpm_WSZ8Cm/.INSTALL: línea 8: _printf: no se encontró la orden
/tmp/alpm_WSZ8Cm/.INSTALL: línea 12: setaf: no se encontró la orden
Archdroid-DeepOrange
/tmp/alpm_WSZ8Cm/.INSTALL: línea 8: _printf: no se encontró la orden
/tmp/alpm_WSZ8Cm/.INSTALL: línea 12: setaf: no se encontró la orden
Archdroid-DeepPurple
/tmp/alpm_WSZ8Cm/.INSTALL: línea 8: _printf: no se encontró la orden
/tmp/alpm_WSZ8Cm/.INSTALL: línea 12: setaf: no se encontró la orden
Archdroid-Green
/tmp/alpm_WSZ8Cm/.INSTALL: línea 8: _printf: no se encontró la orden
/tmp/alpm_WSZ8Cm/.INSTALL: línea 12: setaf: no se encontró la orden
Archdroid-Grey
/tmp/alpm_WSZ8Cm/.INSTALL: línea 8: _printf: no se encontró la orden
/tmp/alpm_WSZ8Cm/.INSTALL: línea 12: setaf: no se encontró la orden
Archdroid-Indigo
/tmp/alpm_WSZ8Cm/.INSTALL: línea 8: _printf: no se encontró la orden
/tmp/alpm_WSZ8Cm/.INSTALL: línea 12: setaf: no se encontró la orden
Archdroid-KellyGreen
/tmp/alpm_WSZ8Cm/.INSTALL: línea 8: _printf: no se encontró la orden
/tmp/alpm_WSZ8Cm/.INSTALL: línea 12: setaf: no se encontró la orden
Archdroid-LightBlue
/tmp/alpm_WSZ8Cm/.INSTALL: línea 8: _printf: no se encontró la orden
/tmp/alpm_WSZ8Cm/.INSTALL: línea 12: setaf: no se encontró la orden
Archdroid-LightGreen
/tmp/alpm_WSZ8Cm/.INSTALL: línea 8: _printf: no se encontró la orden
/tmp/alpm_WSZ8Cm/.INSTALL: línea 12: setaf: no se encontró la orden
Archdroid-Lime
/tmp/alpm_WSZ8Cm/.INSTALL: línea 8: _printf: no se encontró la orden
/tmp/alpm_WSZ8Cm/.INSTALL: línea 12: setaf: no se encontró la orden
Archdroid-Orange
/tmp/alpm_WSZ8Cm/.INSTALL: línea 8: _printf: no se encontró la orden
/tmp/alpm_WSZ8Cm/.INSTALL: línea 12: setaf: no se encontró la orden
Archdroid-Pink
/tmp/alpm_WSZ8Cm/.INSTALL: línea 8: _printf: no se encontró la orden
/tmp/alpm_WSZ8Cm/.INSTALL: línea 12: setaf: no se encontró la orden
Archdroid-Purple
/tmp/alpm_WSZ8Cm/.INSTALL: línea 8: _printf: no se encontró la orden
/tmp/alpm_WSZ8Cm/.INSTALL: línea 12: setaf: no se encontró la orden
Archdroid-Red
/tmp/alpm_WSZ8Cm/.INSTALL: línea 8: _printf: no se encontró la orden
/tmp/alpm_WSZ8Cm/.INSTALL: línea 12: setaf: no se encontró la orden
Archdroid-Shamrock
/tmp/alpm_WSZ8Cm/.INSTALL: línea 8: _printf: no se encontró la orden
/tmp/alpm_WSZ8Cm/.INSTALL: línea 12: setaf: no se encontró la orden
Archdroid-Teal
/tmp/alpm_WSZ8Cm/.INSTALL: línea 8: _printf: no se encontró la orden
/tmp/alpm_WSZ8Cm/.INSTALL: línea 12: setaf: no se encontró la orden
Archdroid-Yellow
/tmp/alpm_WSZ8Cm/.INSTALL: línea 3: _printf: no se encontró la orden
/tmp/alpm_WSZ8Cm/.INSTALL: línea 12: setaf: no se encontró la orden
Credits
to
Google,
Ubuntu
Mono,
Mint-X,
and
Numix
for
this
theme
/tmp/alpm_WSZ8Cm/.INSTALL: línea 3: _printf: no se encontró la orden
/tmp/alpm_WSZ8Cm/.INSTALL: línea 12: setaf: no se encontró la orden
To
enable
icons
for
golang
scripts,
manually
run
this
command:
sudo
echo
"text/x-go
go"
|
sudo
tee
-a
/etc/mime.types
´´´
As you ccan see the _printf function is not present in the .INSTALL therefor makeing an error and fail printing this.
also setaf is not found either.

**Comment by JotaRandom** [comment]
Thanks, release r51 fix the issue

**Comment by GreenRaccoon23** [comment]
Oh ok I see what you were saying now on the AUR. Yeah, I was updating the PKGBUILD, and it took me a couple tries to get it working right. Thanks for the head's up!
