### ISSUE TITLE
Missing icons

### ISSUE THREAD

**Issue by JotaRandom** [GreenRaccoon23/archdroid-icon-theme#3]
I'm sure you not want add more icons but I noticed missing icons in vanilla xfce4
internet-mail <- for exo-mailreader and generic mailreaders.
Thunar <- for... thunar Xp
orage_globaltime <- orage time date, globaltime and calendar
xfce-schedule <- orage as applet
applets-screenshooter <- screenshooter utility
xfce-sensors <- xfce4 sensors app and applet
office-calendar <- generic clock

I'm sure that there are more, but instead of add more, why not mundane symlinks to the generic counterpart? orage, orage as applet and generic clock can share the same icon for exaple.

**Comment by GreenRaccoon23** [comment]
Cool! Thanks! I'll look into that. The default Thunar icon still shows up though, right?

**Comment by JotaRandom** [comment]
right, is a hammer.
also the internet-mail is default to a blank space aestetical bad with all the other icons correctly redered.
that is a comon issue with all the GNOME centric themes.
